load('config.js');

function execute() {
    return Response.success([
        {title: "日本H漫", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&category=1", script: "gen.js"},
        {title: "韩国H漫", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&category=2", script: "gen.js"},
        
        {title: "3P", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=1", script: "gen.js"},
        {title: "BL", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=2", script: "gen.js"},
        {title: "cosplay", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=3", script: "gen.js"},
        {title: "M男", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=4", script: "gen.js"},
        {title: "NTR", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=5", script: "gen.js"},
        {title: "PUA", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=6", script: "gen.js"},
        {title: "暗黑皮肤", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=7", script: "gen.js"},
        {title: "比基尼", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=8", script: "gen.js"},
        {title: "处女", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=9", script: "gen.js"},
        {title: "大屁股", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=10", script: "gen.js"},
        {title: "大阴茎", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=11", script: "gen.js"},
        {title: "单男", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=12", script: "gen.js"},
        {title: "单女", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=13", script: "gen.js"},
        {title: "调教", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=14", script: "gen.js"},
        {title: "扶她futa", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=15", script: "gen.js"},
        {title: "肛交", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=16", script: "gen.js"},
        {title: "肛门", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=17", script: "gen.js"},
        {title: "高潮潮吹", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=18", script: "gen.js"},
        {title: "黑丝丝袜", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=19", script: "gen.js"},
        {title: "后宫", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=20", script: "gen.js"},
        {title: "护士", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=21", script: "gen.js"},
        {title: "怀孕", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=22", script: "gen.js"},
        {title: "姐姐", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=23", script: "gen.js"},
        {title: "巨尻", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=24", script: "gen.js"},
        {title: "口交", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=25", script: "gen.js"},
        {title: "老师", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=26", script: "gen.js"},
        {title: "连裤袜", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=27", script: "gen.js"},
        {title: "恋父", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=28", script: "gen.js"},
        {title: "两穴同时插入", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=29", script: "gen.js"},
        {title: "露出", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=30", script: "gen.js"},
        {title: "萝莉", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=31", script: "gen.js"},
        {title: "马尾辫", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=32", script: "gen.js"},
        {title: "卖淫", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=33", script: "gen.js"},
        {title: "猫女", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=34", script: "gen.js"},
        {title: "毛茸茸", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=35", script: "gen.js"},
        {title: "母亲", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=36", script: "gen.js"},
        {title: "母乳", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=37", script: "gen.js"},
        {title: "内射中出", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=38", script: "gen.js"},
        {title: "内衣", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=39", script: "gen.js"},
        {title: "女同百合", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=40", script: "gen.js"},
        {title: "女学生制服", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=41", script: "gen.js"},
        {title: "破处", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=42", script: "gen.js"},
        {title: "强奸", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=43", script: "gen.js"},
        {title: "群P", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=44", script: "gen.js"},
        {title: "乳交", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=45", script: "gen.js"},
        {title: "受精", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=46", script: "gen.js"},
        {title: "兽耳", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=47", script: "gen.js"},
        {title: "兽交", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=48", script: "gen.js"},
        {title: "束缚", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=49", script: "gen.js"},
        {title: "双性人", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=50", script: "gen.js"},
        {title: "水手服", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=51", script: "gen.js"},
        {title: "丝袜", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=52", script: "gen.js"},
        {title: "同性", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=53", script: "gen.js"},
        {title: "兔女郎", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=54", script: "gen.js"},
        {title: "性转换", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=55", script: "gen.js"},
        {title: "眼睛", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=56", script: "gen.js"},
        {title: "妖精", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=57", script: "gen.js"},
        {title: "药娘伪娘", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=58", script: "gen.js"},
        {title: "衣领", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=59", script: "gen.js"},
        {title: "泳装", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=60", script: "gen.js"},
        {title: "御姐女王", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=61", script: "gen.js"},
        {title: "援交", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=62", script: "gen.js"},
        {title: "正太控", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=63", script: "gen.js"},
        {title: "制服", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=64", script: "gen.js"},
        {title: "足交", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=65", script: "gen.js"},
        {title: "足控", input: BASE_URL + "/comic/all?sort_field=refreshed_at&sort_order=1&page={{page}}&limit=48&tag_id=66", script: "gen.js"}
    ]);
}