load('config.js');
function execute() {
    return Response.success([
        { title: "16+", input: BASE_URL + "/the-loai/16", script: "gen.js" },
        { title: "18+", input: BASE_URL + "/the-loai/18", script: "gen.js" },
        { title: "19+", input: BASE_URL + "/the-loai/19", script: "gen.js" },
        { title: "3D Hentai", input: BASE_URL + "/the-loai/3d-hentai", script: "gen.js" },
        { title: "3P", input: BASE_URL + "/the-loai/3p", script: "gen.js" },
        { title: "Action", input: BASE_URL + "/the-loai/action", script: "gen.js" },
        { title: "Adult", input: BASE_URL + "/the-loai/adult", script: "gen.js" },
        { title: "Adventure", input: BASE_URL + "/the-loai/adventure", script: "gen.js" },
        { title: "Ahegao", input: BASE_URL + "/the-loai/ahegao", script: "gen.js" },
        { title: "Anal", input: BASE_URL + "/the-loai/anal", script: "gen.js" },
        { title: "Angel", input: BASE_URL + "/the-loai/angel", script: "gen.js" },
        { title: "Ảnh động", input: BASE_URL + "/the-loai/anh-dong", script: "gen.js" },
        { title: "Animal", input: BASE_URL + "/the-loai/animal", script: "gen.js" },
        { title: "Animal girl", input: BASE_URL + "/the-loai/animal-girl", script: "gen.js" },
        { title: "Áo Dài", input: BASE_URL + "/the-loai/ao-dai", script: "gen.js" },
        { title: "Apron", input: BASE_URL + "/the-loai/apron", script: "gen.js" },
        { title: "Armpit", input: BASE_URL + "/the-loai/armpit", script: "gen.js" },
        { title: "Artist CG", input: BASE_URL + "/the-loai/artist-cg", script: "gen.js" },
        { title: "Based Game", input: BASE_URL + "/the-loai/based-game", script: "gen.js" },
        { title: "BBM", input: BASE_URL + "/the-loai/bbm", script: "gen.js" },
        { title: "BBW", input: BASE_URL + "/the-loai/bbw", script: "gen.js" },
        { title: "BDSM", input: BASE_URL + "/the-loai/bdsm", script: "gen.js" },
        { title: "Bestiality", input: BASE_URL + "/the-loai/bestiality", script: "gen.js" },
        { title: "Big Ass", input: BASE_URL + "/the-loai/big-ass", script: "gen.js" },
        { title: "Big Boobs", input: BASE_URL + "/the-loai/big-boobs", script: "gen.js" },
        { title: "Big Penis", input: BASE_URL + "/the-loai/big-penis", script: "gen.js" },
        { title: "Blackmail", input: BASE_URL + "/the-loai/blackmail", script: "gen.js" },
        { title: "Bloomers", input: BASE_URL + "/the-loai/bloomers", script: "gen.js" },
        { title: "BlowJobs", input: BASE_URL + "/the-loai/blowjobs", script: "gen.js" },
        { title: "Body Swap", input: BASE_URL + "/the-loai/body-swap", script: "gen.js" },
        { title: "Bodysuit", input: BASE_URL + "/the-loai/bodysuit", script: "gen.js" },
        { title: "Bondage", input: BASE_URL + "/the-loai/bondage", script: "gen.js" },
        { title: "Breast Sucking", input: BASE_URL + "/the-loai/breast-sucking", script: "gen.js" },
        { title: "BreastJobs", input: BASE_URL + "/the-loai/breastjobs", script: "gen.js" },
        { title: "Brocon", input: BASE_URL + "/the-loai/brocon", script: "gen.js" },
        { title: "Brother", input: BASE_URL + "/the-loai/brother", script: "gen.js" },
        { title: "Business Suit", input: BASE_URL + "/the-loai/business-suit", script: "gen.js" },
        { title: "Catgirls", input: BASE_URL + "/the-loai/catgirls", script: "gen.js" },
        { title: "Che ít", input: BASE_URL + "/the-loai/che-it", script: "gen.js" },
        { title: "Che nhiều", input: BASE_URL + "/the-loai/che-nhieu", script: "gen.js" },
        { title: "Cheating", input: BASE_URL + "/the-loai/cheating", script: "gen.js" },
        { title: "Chikan", input: BASE_URL + "/the-loai/chikan", script: "gen.js" },
        { title: "Chinese Dress", input: BASE_URL + "/the-loai/chinese-dress", script: "gen.js" },
        { title: "Có che", input: BASE_URL + "/the-loai/co-che", script: "gen.js" },
        { title: "Comedy", input: BASE_URL + "/the-loai/comedy", script: "gen.js" },
        { title: "Comic", input: BASE_URL + "/the-loai/comic", script: "gen.js" },
        { title: "Con gái", input: BASE_URL + "/the-loai/con-gai", script: "gen.js" },
        { title: "Condom", input: BASE_URL + "/the-loai/condom", script: "gen.js" },
        { title: "Công Sở", input: BASE_URL + "/the-loai/cong-so", script: "gen.js" },
        { title: "Cosplay", input: BASE_URL + "/the-loai/cosplay", script: "gen.js" },
        { title: "Cousin", input: BASE_URL + "/the-loai/cousin", script: "gen.js" },
        { title: "Crotch Tattoo", input: BASE_URL + "/the-loai/crotch-tattoo", script: "gen.js" },
        { title: "Cunnilingus", input: BASE_URL + "/the-loai/cunnilingus", script: "gen.js" },
        { title: "Dark Skin", input: BASE_URL + "/the-loai/dark-skin", script: "gen.js" },
        { title: "Daughter", input: BASE_URL + "/the-loai/daughter", script: "gen.js" },
        { title: "Deepthroat", input: BASE_URL + "/the-loai/deepthroat", script: "gen.js" },
        { title: "Demon", input: BASE_URL + "/the-loai/demon", script: "gen.js" },
        { title: "DemonGirl", input: BASE_URL + "/the-loai/demongirl", script: "gen.js" },
        { title: "Devil", input: BASE_URL + "/the-loai/devil", script: "gen.js" },
        { title: "DevilGirl", input: BASE_URL + "/the-loai/devilgirl", script: "gen.js" },
        { title: "Dirty", input: BASE_URL + "/the-loai/dirty", script: "gen.js" },
        { title: "Dirty Old Man", input: BASE_URL + "/the-loai/dirty-old-man", script: "gen.js" },
        { title: "DogGirl", input: BASE_URL + "/the-loai/doggirl", script: "gen.js" },
        { title: "Double Penetration", input: BASE_URL + "/the-loai/double-penetration", script: "gen.js" },
        { title: "Doujinshi", input: BASE_URL + "/the-loai/doujinshi", script: "gen.js" },
        { title: "Drama", input: BASE_URL + "/the-loai/drama", script: "gen.js" },
        { title: "Drug", input: BASE_URL + "/the-loai/drug", script: "gen.js" },
        { title: "Đã full", input: BASE_URL + "/the-loai/da-full", script: "gen.js" },
        { title: "Ecchi", input: BASE_URL + "/the-loai/ecchi", script: "gen.js" },
        { title: "Echi", input: BASE_URL + "/the-loai/echi", script: "gen.js" },
        { title: "Elder Sister", input: BASE_URL + "/the-loai/elder-sister", script: "gen.js" },
        { title: "Elf", input: BASE_URL + "/the-loai/elf", script: "gen.js" },
        { title: "Exhibitionism", input: BASE_URL + "/the-loai/exhibitionism", script: "gen.js" },
        { title: "Fantasy", input: BASE_URL + "/the-loai/fantasy", script: "gen.js" },
        { title: "Father", input: BASE_URL + "/the-loai/father", script: "gen.js" },
        { title: "Femdom", input: BASE_URL + "/the-loai/femdom", script: "gen.js" },
        { title: "Fingering", input: BASE_URL + "/the-loai/fingering", script: "gen.js" },
        { title: "Footjob", input: BASE_URL + "/the-loai/footjob", script: "gen.js" },
        { title: "Foxgirls", input: BASE_URL + "/the-loai/foxgirls", script: "gen.js" },
        { title: "Full Color", input: BASE_URL + "/the-loai/full-color", script: "gen.js" },
        { title: "Furry", input: BASE_URL + "/the-loai/furry", script: "gen.js" },
        { title: "Futanari", input: BASE_URL + "/the-loai/futanari", script: "gen.js" },
        { title: "GangBang", input: BASE_URL + "/the-loai/gangbang", script: "gen.js" },
        { title: "Garter Belts", input: BASE_URL + "/the-loai/garter-belts", script: "gen.js" },
        { title: "Gender Bender", input: BASE_URL + "/the-loai/gender-bender", script: "gen.js" },
        { title: "Ghost", input: BASE_URL + "/the-loai/ghost", script: "gen.js" },
        { title: "Glasses", input: BASE_URL + "/the-loai/glasses", script: "gen.js" },
        { title: "Gothic Lolita", input: BASE_URL + "/the-loai/gothic-lolita", script: "gen.js" },
        { title: "Group", input: BASE_URL + "/the-loai/group", script: "gen.js" },
        { title: "Guro", input: BASE_URL + "/the-loai/guro", script: "gen.js" },
        { title: "Hài hước", input: BASE_URL + "/the-loai/hai-huoc", script: "gen.js" },
        { title: "Hairy", input: BASE_URL + "/the-loai/hairy", script: "gen.js" },
        { title: "Handjob", input: BASE_URL + "/the-loai/handjob", script: "gen.js" },
        { title: "Harem", input: BASE_URL + "/the-loai/harem", script: "gen.js" },
        { title: "Hentai", input: BASE_URL + "/the-loai/hentai", script: "gen.js" },
        { title: "HentaiVN", input: BASE_URL + "/the-loai/hentaivn", script: "gen.js" },
        { title: "Hiện đại", input: BASE_URL + "/the-loai/hien-dai", script: "gen.js" },
        { title: "Historical", input: BASE_URL + "/the-loai/historical", script: "gen.js" },
        { title: "Horror", input: BASE_URL + "/the-loai/horror", script: "gen.js" },
        { title: "Housewife", input: BASE_URL + "/the-loai/housewife", script: "gen.js" },
        { title: "Humiliation", input: BASE_URL + "/the-loai/humiliation", script: "gen.js" },
        { title: "Idol", input: BASE_URL + "/the-loai/idol", script: "gen.js" },
        { title: "Imouto", input: BASE_URL + "/the-loai/imouto", script: "gen.js" },
        { title: "Incest", input: BASE_URL + "/the-loai/incest", script: "gen.js" },
        { title: "Insect (Côn Trùng)", input: BASE_URL + "/the-loai/insect-con-trung", script: "gen.js" },
        { title: "Invisible", input: BASE_URL + "/the-loai/invisible", script: "gen.js" },
        { title: "Isekai", input: BASE_URL + "/the-loai/isekai", script: "gen.js" },
        { title: "Không che", input: BASE_URL + "/the-loai/khong-che", script: "gen.js" },
        { title: "không NTR", input: BASE_URL + "/the-loai/khong-ntr", script: "gen.js" },
        { title: "Kimono", input: BASE_URL + "/the-loai/kimono", script: "gen.js" },
        { title: "Kissing", input: BASE_URL + "/the-loai/kissing", script: "gen.js" },
        { title: "Kuudere", input: BASE_URL + "/the-loai/kuudere", script: "gen.js" },
        { title: "Lãng Mạn", input: BASE_URL + "/the-loai/lang-man", script: "gen.js" },
        { title: "Lolicon", input: BASE_URL + "/the-loai/lolicon", script: "gen.js" },
        { title: "Maids", input: BASE_URL + "/the-loai/maids", script: "gen.js" },
        { title: "MANGA", input: BASE_URL + "/the-loai/manga", script: "gen.js" },
        { title: "Manhua", input: BASE_URL + "/the-loai/manhua", script: "gen.js" },
        { title: "Manhwa", input: BASE_URL + "/the-loai/manhwa", script: "gen.js" },
        { title: "Masturbation", input: BASE_URL + "/the-loai/masturbation", script: "gen.js" },
        { title: "Mature", input: BASE_URL + "/the-loai/mature", script: "gen.js" },
        { title: "Miko", input: BASE_URL + "/the-loai/miko", script: "gen.js" },
        { title: "Milf", input: BASE_URL + "/the-loai/milf", script: "gen.js" },
        { title: "Mind Break", input: BASE_URL + "/the-loai/mind-break", script: "gen.js" },
        { title: "Mind Control", input: BASE_URL + "/the-loai/mind-control", script: "gen.js" },
        { title: "Mizugi", input: BASE_URL + "/the-loai/mizugi", script: "gen.js" },
        { title: "Monster", input: BASE_URL + "/the-loai/monster", script: "gen.js" },
        { title: "Monstergirl", input: BASE_URL + "/the-loai/monstergirl", script: "gen.js" },
        { title: "Mother", input: BASE_URL + "/the-loai/mother", script: "gen.js" },
        { title: "Nakadashi", input: BASE_URL + "/the-loai/nakadashi", script: "gen.js" },
        { title: "Netori", input: BASE_URL + "/the-loai/netori", script: "gen.js" },
        { title: "Ngôn Tình", input: BASE_URL + "/the-loai/ngon-tinh", script: "gen.js" },
        { title: "Non-hen", input: BASE_URL + "/the-loai/non-hen", script: "gen.js" },
        { title: "NTR", input: BASE_URL + "/the-loai/ntr", script: "gen.js" },
        { title: "Nun", input: BASE_URL + "/the-loai/nun", script: "gen.js" },
        { title: "Nurse", input: BASE_URL + "/the-loai/nurse", script: "gen.js" },
        { title: "Old Man", input: BASE_URL + "/the-loai/old-man", script: "gen.js" },
        { title: "One shot", input: BASE_URL + "/the-loai/one-shot", script: "gen.js" },
        { title: "Oneshot", input: BASE_URL + "/the-loai/oneshot", script: "gen.js" },
        { title: "Oral", input: BASE_URL + "/the-loai/oral", script: "gen.js" },
        { title: "Osananajimi", input: BASE_URL + "/the-loai/osananajimi", script: "gen.js" },
        { title: "Paizuri", input: BASE_URL + "/the-loai/paizuri", script: "gen.js" },
        { title: "Pantyhose", input: BASE_URL + "/the-loai/pantyhose", script: "gen.js" },
        { title: "Ponytail", input: BASE_URL + "/the-loai/ponytail", script: "gen.js" },
        { title: "Pregnant", input: BASE_URL + "/the-loai/pregnant", script: "gen.js" },
        { title: "Prostitution", input: BASE_URL + "/the-loai/prostitution", script: "gen.js" },
        { title: "Rape", input: BASE_URL + "/the-loai/rape", script: "gen.js" },
        { title: "Riêng tư", input: BASE_URL + "/the-loai/rieng-tu", script: "gen.js" },
        { title: "Rimjob", input: BASE_URL + "/the-loai/rimjob", script: "gen.js" },
        { title: "Romanc", input: BASE_URL + "/the-loai/romanc", script: "gen.js" },
        { title: "Romance", input: BASE_URL + "/the-loai/romance", script: "gen.js" },
        { title: "Ryona", input: BASE_URL + "/the-loai/ryona", script: "gen.js" },
        { title: "Scat", input: BASE_URL + "/the-loai/scat", script: "gen.js" },
        { title: "School Uniform", input: BASE_URL + "/the-loai/school-uniform", script: "gen.js" },
        { title: "SchoolGirl", input: BASE_URL + "/the-loai/schoolgirl", script: "gen.js" },
        { title: "Series", input: BASE_URL + "/the-loai/series", script: "gen.js" },
        { title: "Sex Toys", input: BASE_URL + "/the-loai/sex-toys", script: "gen.js" },
        { title: "Shimapan", input: BASE_URL + "/the-loai/shimapan", script: "gen.js" },
        { title: "Short Hentai", input: BASE_URL + "/the-loai/short-hentai", script: "gen.js" },
        { title: "Shota", input: BASE_URL + "/the-loai/shota", script: "gen.js" },
        { title: "Shoujo", input: BASE_URL + "/the-loai/shoujo", script: "gen.js" },
        { title: "Siscon", input: BASE_URL + "/the-loai/siscon", script: "gen.js" },
        { title: "Sister", input: BASE_URL + "/the-loai/sister", script: "gen.js" },
        { title: "Slave", input: BASE_URL + "/the-loai/slave", script: "gen.js" },
        { title: "Sleeping", input: BASE_URL + "/the-loai/sleeping", script: "gen.js" },
        { title: "SM/BDSM/SUB-DOM", input: BASE_URL + "/the-loai/sm-bdsm-sub-dom", script: "gen.js" },
        { title: "Small Boobs", input: BASE_URL + "/the-loai/small-boobs", script: "gen.js" },
        { title: "Smut", input: BASE_URL + "/the-loai/smut", script: "gen.js" },
        { title: "Son", input: BASE_URL + "/the-loai/son", script: "gen.js" },
        { title: "Sports", input: BASE_URL + "/the-loai/sports", script: "gen.js" },
        { title: "Stockings", input: BASE_URL + "/the-loai/stockings", script: "gen.js" },
        { title: "Supernatural", input: BASE_URL + "/the-loai/supernatural", script: "gen.js" },
        { title: "Sweating", input: BASE_URL + "/the-loai/sweating", script: "gen.js" },
        { title: "Swimsuit", input: BASE_URL + "/the-loai/swimsuit", script: "gen.js" },
        { title: "Tall Girl", input: BASE_URL + "/the-loai/tall-girl", script: "gen.js" },
        { title: "Teacher", input: BASE_URL + "/the-loai/teacher", script: "gen.js" },
        { title: "Tentacles", input: BASE_URL + "/the-loai/tentacles", script: "gen.js" },
        { title: "Time Stop", input: BASE_URL + "/the-loai/time-stop", script: "gen.js" },
        { title: "Tình Cảm", input: BASE_URL + "/the-loai/tinh-cam", script: "gen.js" },
        { title: "Tomboy", input: BASE_URL + "/the-loai/tomboy", script: "gen.js" },
        { title: "Tracksuit", input: BASE_URL + "/the-loai/tracksuit", script: "gen.js" },
        { title: "Transformation", input: BASE_URL + "/the-loai/transformation", script: "gen.js" },
        { title: "Trap", input: BASE_URL + "/the-loai/trap", script: "gen.js" },
        { title: "Truyện chữ", input: BASE_URL + "/the-loai/truyen-chu", script: "gen.js" },
        { title: "Truyện Màu", input: BASE_URL + "/the-loai/truyen-mau", script: "gen.js" },
        { title: "Truyện tranh 18+", input: BASE_URL + "/the-loai/truyen-tranh-18", script: "gen.js" },
        { title: "Truyện Việt", input: BASE_URL + "/the-loai/truyen-viet", script: "gen.js" },
        { title: "Tsundere", input: BASE_URL + "/the-loai/tsundere", script: "gen.js" },
        { title: "Twins", input: BASE_URL + "/the-loai/twins", script: "gen.js" },
        { title: "Twintails", input: BASE_URL + "/the-loai/twintails", script: "gen.js" },
        { title: "Vampire", input: BASE_URL + "/the-loai/vampire", script: "gen.js" },
        { title: "Vanilla", input: BASE_URL + "/the-loai/vanilla", script: "gen.js" },
        { title: "Vếu to", input: BASE_URL + "/the-loai/veu-to", script: "gen.js" },
        { title: "Virgin", input: BASE_URL + "/the-loai/virgin", script: "gen.js" },
        { title: "Webtoon", input: BASE_URL + "/the-loai/webtoon", script: "gen.js" },
        { title: "X-ray", input: BASE_URL + "/the-loai/x-ray", script: "gen.js" },
        { title: "Yandere", input: BASE_URL + "/the-loai/yandere", script: "gen.js" },
        { title: "Yaoi", input: BASE_URL + "/the-loai/yaoi", script: "gen.js" },
        { title: "Yuri", input: BASE_URL + "/the-loai/yuri", script: "gen.js" },
        { title: "Zombie", input: BASE_URL + "/the-loai/zombie", script: "gen.js" }
    ]);
}